### ISSUE TITLE
Missing applications

### ISSUE THREAD

**Issue by wizziLalev** [technorabilia/portainer-templates#5]
Hi All,

Is it me only or some applications available as repos from Linuxserver.io are missing in the templates?
I am seeing that containers like [Plowarr](https://hub.docker.com/r/linuxserver/prowlarr) are not available even still maintained by Linuxserver.io

Based on data from [Images List](https://fleet.linuxserver.io/api/v1/images)
- 175 containers available
- 27 are deprecated

that leave us with 148 available while 144 are in the current json.

Best,

**Comment by technorabilia** [comment]
Yes, you are right.

This is because e.g. Prowlarr does not have a [`main`](https://github.com/linuxserver/docker-prowlarr) branch.

Prowlarr is based on version [`0.2.0-nightly`](https://fleet.linuxserver.io/image?name=linuxserver/prowlarr) and the accompanying [`nightly`](https://github.com/linuxserver/docker-prowlarr/tree/nightly) branch.

Others like Readarr are based on the [`develop`](https://github.com/linuxserver/docker-readarr/tree/develop) branch and so on.

I only process the `main` branch as I could not find a generic way to process other branches as well.
